[package]
name = "minhook-sys"
version = "0.1.0"
authors = ["metherul <metherul@protonmail.com>"]
edition = "2018"
repository = "https://github.com/metherul/minhook-sys"
links = "minhook.x64d"

[lib]
name = "minhook_sys"
path = "lib.rs"

[dependencies]
